### PR TITLE
Changed to Terminal execution

### PR DESCRIPTION
**Pull request by Moejoe90**
The previous commands didn't work on Docker nor my Linux host environment, i have managed to run hello world but when i tried to compile blue-eth i was faced with glyph generation problem. 
After investigating more i realized that there is no log command in the Linux Terminal nor GNU make , i think log might work on a mac system i'm not sure, in all cases i had to relay on using the shell terminal to run and things worked perfectly for me. 
If this works on a mac system then its a the best method so far that proves cross platform compilation

### CODE REVIEW

**Comment by parkerhoyes** [comment]
To me it looks like either the Makefile you're using is outdated, or you're using an outdated version of the SDK. There is no reason to modify `Makefile.glyphs` to make this work.

`log` is defined in `Makefile.defines` in the SDK, and its definition depends on whether or not the `VERBOSE` environment variable is set.

We don't use Docker anymore to manage the development environment, so that may be the source of the problem. Try setting up your development environment again using the instructions [here](https://github.com/LedgerHQ/blue-devenv).

Also, currently not all apps have been updated to the latest build process, so you might just have to wait a bit longer for everything to be in sync. In the mean time, I know that the sample apps build fine with the latest SDK and development environment, without any modifications.

**Comment by Moejoe90** [comment]
I have indeed set my development environment using [link](https://github.com/LedgerHQ/blue-devenv) everything was set and the samples worked fine in both Docker and Local Environment. 
You have a point where `Makefile` for [This](https://github.com/LedgerHQ/blue-app-eth) project is outdated. 
Even tough in theory i think using docker as a way to unify Dev environments is interesting i think practically it causes more problems in terms of time and flexibility. 
I have managed to run the old Make-files of different Dev projects including [This](https://github.com/LedgerHQ/blue-app-eth) and they worked fine with this tweak. but i will look into modifying the build files and copy the samples on how they utilize glyphs

**Comment by rstormsf** [comment]
the `icon.py` doesn't produce any files for glyphs.c or glyphs.h for blue-app-eth

**Comment by rstormsf** [comment]
@parkerhoyes 
In file included from /usr/include/stdint.h:52:
In file included from /usr/include/sys/_types.h:32:
/usr/include/sys/cdefs.h:761:2: error: Unsupported architecture
#error Unsupported architecture
 ^
In file included from /Users/rstorm/repos/ledger/mac/nanos-secure-sdk-nanos-1314/src/os.c:18:
In file included from /Users/rstorm/repos/ledger/mac/nanos-secure-sdk-nanos-1314/include/os.h:59:
In file included from /Users/rstorm/repos/ledger/mac/nanos-secure-sdk-nanos-1314/include/core_sc000.h:119:
In file included from /Users/rstorm/repos/ledger/mac/clang-arm-fropi/bin/../lib/clang/4.0.0/include/stdint.h:63:
In file included from /usr/include/stdint.h:52:
In file included from /usr/include/sys/_types.h:33:
/usr/include/machine/_types.h:34:2: error: architecture not supported

under osx

**Pull request closed without merging**
